# Site
title: M.D. Blog
url: https://blog.aoramd.moe
lang: zh-Hans
email: auroravmd@outlook.com
github_username:  AoraMD

# Build Settings
markdown: kramdown
color_scheme: bw
exclude:
  - Gemfile
  - Gemfile.lock